services:
  jellyfin:
    container_name: jellyfin
    image: lscr.io/linuxserver/jellyfin:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ./configs/mediarr/jellyfin:/config
      - ./data:/data
    ports:
      - 8096:8096
    labels:
      - tsdproxy.enable=true
    restart: unless-stopped

  #   firefox:
  #     image: lscr.io/linuxserver/firefox:latest
  #     container_name: firefox
  #     security_opt:
  #       - seccomp:unconfined
  #     environment:
  #       - PUID=1000
  #       - PGID=1000
  #       - TZ=TIME_ZONE
  #       - DRINODE=/dev/dri/renderD128
  #       - DISABLE_IPV6=true
  #       - DOCKER_MODS=linuxserver/mods:firefox-fonts
  #     volumes: - ./configs/firefox:/config
  #     ports:
  #       - 3001:3001
  #     networks:
  #       - firefox
  #     shm_size: "1gb"
  #     devices:
  #       - /dev/dri/renderD128:/dev/dri/renderD128
  #     group_add:
  #       - "109"
  #     restart: unless-stopped
  #   duplicati:
  #     image: lscr.io/linuxserver/duplicati:latest
  #     container_name: duplicati
  #     environment:
  #       - PUID=1000
  #       - PGID=1000
  #       - TZ=TIME_ZONE
  #     volumes:
  #       - ./configs/duplicati/config:/config
  #       - ./configs:/source
  #       - ./docker-compose.yml:/source/docker-compose.yml
  #       - ./configs/duplicati/restore:/restore
  #     networks:
  #       - duplicati
  #     ports:
  #       - 8200:8200
  #     restart: unless-stopped
  #   bazarr:
  #     image: lscr.io/linuxserver/bazarr:latest
  #     container_name: bazarr
  #     hostname: bazarr
  #     networks:
  #       - mediarr
  #     environment:
  #       - PUID=1000
  #       - PGID=1000
  #       - TZ=TIME_ZONE
  #     volumes:
  #       - ./configs/mediarr/bazarr:/config
  #       - myMedia:/mnt/media
  #     ports:
  #       - 6767:6767
  #     restart: unless-stopped
  #     depends_on:
  #       - sonarr
  #       - radarr

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    hostname: jellyseerr
    user: 1000:1000
    environment:
      - TZ=TIME_ZONE
    ports:
      - 5055:5055
    volumes:
      - ./configs/mediarr/jellyseerr:/app/config
    labels:
      - tsdproxy.enable=true
    restart: unless-stopped
    depends_on:
      #   - sonarr
      - radarr

  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    # network_mode: service:gluetun
    # networks:
    #   - mediarr
    environment:
      - puid=1000
      - pgid=1000
      - tz=africa/casablanca
    volumes:
      - ./configs/mediarr/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    # depends_on:
    #   - flaresolverr

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    # network_mode: service:gluetun
    # networks:
    #   - mediarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=TIME_ZONE
    volumes:
      - ./configs/mediarr/radarr:/config
      - ./data:/data
    ports:
      - 7878:7878
    restart: unless-stopped
    depends_on:
      - prowlarr
      # - qbittorrent
      - jellyfin

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    # network_mode: service:gluetun
    # networks:
    #   - mediarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=TIME_ZONE
    volumes:
      - ./configs/mediarr/sonarr:/config
      - ./data:/data
      # - myDlFolders:/mnt/downloads
    depends_on:
      - prowlarr
      # - qbittorrent
      - jellyfin
    ports:
      - 8989:8989
    restart: unless-stopped

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    hostname: flaresolverr
    environment:
      - LOG_LEVEL=info
      - TZ=TIME_ZONE
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: service:gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=TIME_ZONE
      - WEBUI_PORT=8080
    volumes:
      - ./configs/mediarr/qbittorrent:/config
      - ./data:/data
    restart: unless-stopped

  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    restart: always
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      # - 9696:9696 # Prowlarr Web UI
      # - 7878:7878 # Radarr Web UI
      # - 8989:8989 # Sonarr Web UI
      - 8080:8080 # QBittorrent Web UI
    volumes:
      - ./configs/gluetun:/gluetun
      - ./configs/gluetun/wireguard/wireguard.conf:/gluetun/wireguard/wg0.conf
    environment:
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${VPN_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${VPN_ADDRESSES}
      - SERVER_COUNTRIES=Switzerland

  tsdproxy:
    image: almeidapaulopt/tsdproxy:2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./configs/tsdproxy/data:/data
      - ./configs/tsdproxy/config:/config
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
    ports:
      - "8888:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

# networks:
#   mediarr:
#     driver: bridge

# volumes:
#   myMedia:
#     driver: local
#     driver_opts:
#       type: none
#       o: bind
#       device: /mnt/media
#   myDlFolders:
#     driver: local
#     driver_opts:
#       type: none
#       o: bind
#       device: /mnt/HDD/downloads
