services:
  jellyfin:
    container_name: jellyfin
    image: lscr.io/linuxserver/jellyfin:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ./configs/mediarr/jellyfin:/config
      - ${DATA_DIR}:/data
    ports:
      - 8096:8096
    labels:
      - tsdproxy.enable=true
    restart: unless-stopped

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    hostname: jellyseerr
    user: 1000:1000
    environment:
      - TZ=TIME_ZONE
    ports:
      - 5055:5055
    volumes:
      - ./configs/mediarr/jellyseerr:/app/config
    labels:
      - tsdproxy.enable=true
    restart: unless-stopped
    depends_on:
      - sonarr
      - radarr

  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - puid=1000
      - pgid=1000
      - tz=africa/casablanca
    volumes:
      - ./configs/mediarr/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    depends_on:
      - flaresolverr

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=TIME_ZONE
    volumes:
      - ./configs/mediarr/radarr:/config
      - ${DATA_DIR}:/data
    ports:
      - 7878:7878
    restart: unless-stopped
    depends_on:
      - prowlarr
      - qbittorrent
      - jellyfin

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=TIME_ZONE
    volumes:
      - ./configs/mediarr/sonarr:/config
      - ${DATA_DIR}:/data
    depends_on:
      - prowlarr
      - qbittorrent
      - jellyfin
    ports:
      - 8989:8989
    restart: unless-stopped

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    hostname: flaresolverr
    environment:
      - LOG_LEVEL=info
      - TZ=TIME_ZONE
    restart: unless-stopped

  qbittorrent:
    image: binhex/arch-qbittorrentvpn:latest
    container_name: qbittorrent
    restart: unless-stopped
    privileged: true
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    ports:
      - "8080:8080"
      # - "8118:8118"
      # - "9118:9118"
      # - "58946:58946"
      # - "58946:58946/udp"
    volumes:
      - ${DATA_DIR}:/data
      - ./configs/qbittorrent:/config
      # - /etc/localtime:/etc/localtime:ro
    environment:
      - VPN_ENABLED=yes
      - VPN_PROV=airvpn
      - VPN_CLIENT=wireguard
      # - VPN_OPTIONS=<additional openvpn cli options>
      # - ENABLE_STARTUP_SCRIPTS=<yes|no>
      # - ENABLE_PRIVOXY=<yes|no>
      - STRICT_PORT_FORWARD=no
      - USERSPACE_WIREGUARD=no
      # - ENABLE_SOCKS=<yes|no>
      # - SOCKS_USER=<socks username>
      # - SOCKS_PASS=<socks password>
      - LAN_NETWORK=192.168.1.0/24
      # - NAME_SERVERS=<name server ip(s)>
      # - VPN_INPUT_PORTS=<port number(s)>
      # - VPN_OUTPUT_PORTS=<port number(s)>
      - DEBUG=false
      - WEBUI_PORT=8080
      # - HEALTHCHECK_COMMAND=<command>
      # - HEALTHCHECK_ACTION=<action>
      # - HEALTHCHECK_HOSTNAME=<hostname>
      # - UMASK=<umask for created files>
      - PUID=1000
      - PGID=1000

  tsdproxy:
    image: almeidapaulopt/tsdproxy:2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./configs/tsdproxy/data:/data
      - ./configs/tsdproxy/config:/config
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
    ports:
      - "8888:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  autobrr:
    container_name: autobrr
    image: ghcr.io/autobrr/autobrr:latest
    restart: unless-stopped
    #logging:
    #  driver: json-file
    #  options:
    #    max-file: ${DOCKERLOGGING_MAXFILE}
    #    max-size: ${DOCKERLOGGING_MAXSIZE}
    user: 1000:1000
    environment:
      - TZ=${TIME_ZONE}
    volumes:
      - ./configs/mediarr/autobrr:/config
    ports:
      - 7474:7474
